version: '3.8'

services:
  # Base de Datos: El corazón donde se guardarán los reportes
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin_municipio
      POSTGRES_PASSWORD: password_seguro123
      POSTGRES_DB: reportes_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # Backend: Aquí irá nuestra lógica de negocio
  backend:
    build: ./backend
    restart: on-failure
    depends_on:
      - db

  # Frontend: La interfaz que usará el ciudadano
  frontend:
    build: ./frontend
    restart: on-failure

volumes:
  db_data: